title: FlexSearch
baseline: Client side full-text search for Cecil.
description: Demo of the FlexSearch component theme for Cecil.
baseurl: http://localhost:8000/
theme:
  - flexsearch
flexsearch:
  sections:
    docs:
      limit: 5
    blog:
      limit: 3
      split: false
      date: true
language: en
languages:
  - code: en
    name: English
    locale: en_US
  - code: fr
    name: Français
    locale: fr_FR
    config:
      baseline: Recherche plein texte côté client pour Cecil.
      menus:
        main:
          - {id: docs, name: Documentation, url: /fr/docs/, weight: 10}
          - {id: blog, name: Blog, url: /fr/blog/, weight: 20}
          - {id: github, name: GitHub, url: 'https://github.com/Cecilapp/theme-flexsearch', weight: 30}
menus:
  main:
    - {id: docs, name: Documentation, url: /docs/, weight: 10}
    - {id: blog, name: Blog, url: /blog/, weight: 20}
    - {id: github, name: GitHub, url: 'https://github.com/Cecilapp/theme-flexsearch', weight: 30}
